name: todos_data_source
description: A generic interface for managing todos.
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  meta: ^1.7.0

dependencies:
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
